# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from pathlib import Path
from silence_cutter import CutterOptions, count_audio_streams, cut_video, default_ffmpeg_path, log_noop, parse_duration
from typing import Any
import ctypes
import os
import sys

__all__ = ['get_version', 'get_ffmpeg_path', 'probe_video', 'process_video']
def get_version() -> str:
    ...

def get_ffmpeg_path() -> str:
    ...

def probe_video(video_path: str) -> dict:
    ...

def process_video(input_path: str, output_path: str, threshold_db: float, min_silence: float, padding: float, min_keep: float, detection_mode: str, mode: str, log_callback: Any) -> dict:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import ctypes
import sys
import os
import pathlib
import silence_cutter